spring.application.name=TravelSmart
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5432/TravelSmart
spring.datasource.username=ahmed
spring.datasource.password=ahmed
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.format.date-time=iso
spring.jpa.show-sql=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging.level.org.springframework.security=DEBUG
# JWT Configuration
jwt.secret=+3ZzcQnpCQH63ty1LWc5GuF3Rj0K5Oe3ZGWWYd25krg=




# Gemini AI Configuration
gemini.api.key=AIzaSyAkMoh2Zwvf1FHMcmmXNsiaaQBXi98Ad7w  
gemini.api.base-url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent