spring.application.name=TravelSmart1
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5432/TravelSmart1
spring.datasource.username=ahmed
spring.datasource.password=ahmed
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.format.date-time=iso
spring.jpa.show-sql=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging.level.org.springframework.security=DEBUG
# JWT Configuration
jwt.secret=z7dvS5KvElU69fDmlzGDsLLI19OjRTJg1osbBnMOqbo=



spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=419b9afd9f46c7
spring.mail.password=4686b74de0c559
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
